### ISSUE TITLE
Tela - Login/Cadastro de Usuário

### ISSUE THREAD

**Issue by femedici** [afmireski/opt120_projeto_final_app#2]
# Description
O front deve fazer a autenticação completa, com verificação por endpoint do login, e cadastro de usuário. Validar o usuário e criar o tempo de sessão no web. 

# Tasks
- [ ] Implementar tela Login
- [ ] Implementar tela Cadastro
- [ ] Implementar fazer teste com dados mockados (teste de fluxo)
- [ ] Implementar integração com a rota do backend

# Requesitos
### Campos 
Login deve ter:
- `RA e senha `

Cadastro deve ter: 
- `Nome, Email, RA, senha`

### Componentes
Visualmente deve ser semelhante com login do sistema da UTFPR (app acadêmico)
