### ISSUE TITLE
Tela - Perfil Usuário

### ISSUE THREAD

**Issue by femedici** [afmireski/opt120_projeto_final_app#4]
# Description
A página deve mostrar as informações do Usuário informadas no cadastro

# Tasks
- [ ] Implementar tela Usuário (Editar/Alterar Senha)
- [ ] Implementar fazer teste com dados mockados (teste de fluxo)
- [ ] Implementar integração com a rota do backend

# Requesitos
### Campos 
Usuário deve ter: 
- `Nome, Email, RA, senha`

### Componentes
Visualmente deve ser semelhante com o sistema da UTFPR (app acadêmico)
